apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-statefulset
  labels:
    app: mongodb
spec:
  serviceName: "mongodb"
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo
          args: ["--auth"]
          envFrom:
          - configMapRef:
              name: mongodb-config
          ports:
          - containerPort: 27017
          volumeMounts:
          - name: pv-data
            mountPath: /var/lib/mongo/data
      volumes:
        - name: pv-data
          persistentVolumeClaim:
            claimName: mongodb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    app: mongodb
spec:
  ports:
    - port: 27017
  type: NodePort
  selector:
    app: mongodb